### PR TITLE
Some improvment propositions

### PR DESCRIPTION
**Pull request by BenoitConnan**
Hello, i was goofing around with pipely and thougth about some changes that could make it nifty.
I hope those changes seems good to you

**My issues :**
No subparser commands, making the cli tool confusing
No way to share data between classes
Executing module with pipely.cli feels ... Weird and non pythonic ? That neatpicking at this point but devil is in the detail

**My solutions**
**Changes from devs' side :**
Adding 'typer' as a cli tool instead of argparse
Using typer to add subparser commands instead of multi value parsing
cleaning some files, removing white spaces, removing python 2 syntax, simplifying project hierarchy

Using importlib to load arbitrary python file (instead of adding them to sys.path )
Use above changes to add a shared dictionnary between pools (simply add an arg when defining a class.__call__ to use it as the context dictionary)

**Changes from users' side:**
instead of python -m pipely.cli --config_file your/path/to.yaml
you have  python -m pipely from-pipeline your/path/to.yaml

also, you don't have to launch pipely from your root anymore
../../../pipeline.yaml and super/duper/secret/project/pipeline.yaml should work as well

### CODE REVIEW

**Comment by BenoitConnan** [comment]
I was a bit too eager to code as always, tell me if you'd prefer for me to open an issue and a merge for each problem I address

**Comment by 5x12** [comment]
Really liked your suggested changes - awesome work! Could you please update the README file to make this PR complete? 
(incl. explanation of sh.dictionary)

**Comment by BenoitConnan** [comment]
Sure, done ;)

**Comment by 5x12** [comment]
I've re-written the README file and changed the example files accordingly. 
I think it's almost ready. The last to-do thing is to add an optional shared dictionary argument (context) for a declarative way as well, just like you did for an imperative one.

**Comment by 5x12** [comment]
@BenoitConnan Let me know if you have time to do it. Otherwise, I may find some free time end of next week.

**Comment by BenoitConnan** [comment]
No problem, i'm on it

**Pull request merged**
